// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
      json['ID'] as String,
      json['Code'] as String?,
      json['Code2'] as String?,
      json['Code3'] as String?,
      json['FullName'] as String?,
      json['FullNameNoAccent'] as String?,
      json['Alias'] as String?,
      json['Gender'] as bool,
      json['Birthplace'] as String?,
      json['Mobile'] as String?,
      json['Email'] as String?,
      json['Avatar'] as String?,
      json['EmailNoDomain'] as String?,
      json['Department'] as int,
      json['DepartmentName'] as String?,
      json['Position'] as int,
      json['PositionName'] as String?,
      json['Modified'] as String?,
      json['Nationality'] as String?,
      json['WorkingPattern'] as String?,
      json['Status'] as int,
      json['SpecialContent'] as String?,
      json['Birthday'] as String?,
      json['Address'] as String?,
      json['IdentityNum'] as String?,
      json['NgayVaoDang'] as String?,
      json['StartDateWork'] as String?,
      json['Base'] as String?,
      json['IDNumber'] as String?,
      json['RewardDiscipline'] as String?,
      json['EstimatedFlightTimeInMonth'] as String?,
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'ID': instance.id,
      'Code': instance.code,
      'Code2': instance.code2,
      'Code3': instance.code3,
      'FullName': instance.fullName,
      'FullNameNoAccent': instance.fullNameNoAccent,
      'Alias': instance.alias,
      'Gender': instance.gender,
      'Birthplace': instance.birthplace,
      'Mobile': instance.mobile,
      'Email': instance.email,
      'Avatar': instance.avatar,
      'EmailNoDomain': instance.emailNoDomain,
      'Department': instance.department,
      'DepartmentName': instance.departmentName,
      'Position': instance.position,
      'PositionName': instance.positionName,
      'Modified': instance.modified,
      'Nationality': instance.nationality,
      'WorkingPattern': instance.workingPattern,
      'Status': instance.status,
      'SpecialContent': instance.specialContent,
      'Birthday': instance.birthday,
      'Address': instance.address,
      'IdentityNum': instance.identityNumber,
      'NgayVaoDang': instance.ngayVaoDang,
      'StartDateWork': instance.startDateWork,
      'Base': instance.base,
      'IDNumber': instance.idNumber,
      'RewardDiscipline': instance.rewardDiscipline,
      'EstimatedFlightTimeInMonth': instance.estimatedFlightTimeInMonth,
    };
